[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore MecHub.csproj"]

[phases.build]
cmds = ["dotnet publish MecHub.csproj --no-restore -c Release -o out"]

[start]
cmd = "dotnet out/MecHub.dll"